apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    app: crud-server
    component: redis
  template:
    metadata:
      name: redis
      labels:
        app: crud-server
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:3.2.0
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 500m
          ports:
            - name: redis-port
              containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: crud-server
    component: redis
spec:
  type: ClusterIP
  selector:
    app: crud-server
    component: redis
  ports:
    - port: 6379
      protocol: TCP
      name: redis-port
