apiVersion: v1
kind: ReplicationController
metadata:
  name: server
spec:
  replicas: 1
  selector:
    app: crud-server
    component: server
  template:
    metadata:
      name: server
      labels:
        app: crud-server
        component: server
    spec:
      containers:
        - name: server
          image: kafkapre/linuxdays2016-simple-crud-server:latest
          ports:
            - name: server-port
              containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: crud-server
    component: server
spec:
  #type: ClusterIP
  selector:
    app: crud-server
    component: server
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: server-port
