apiVersion: v1
kind: ReplicationController
metadata:
  name: server
spec:
  replicas: 1
  selector:
    app: crud-server
    component: server
  template:
    metadata:
      name: server
      labels:
        app: crud-server
        component: server
    spec:
      containers:
        - name: server
          image: kafkapre/linuxdays2016-simple-crud-server:latest
          env:
            - name: REDIS_IP
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: server-port
              containerPort: 3000
              hostPort: 80

